const ADDBANNER = 'ADDBANNER';
const ADDPERSONALIZED = 'ADDPERSONALIZED';
const ADDPLAYLIST = 'ADDPLAYLIST';
const ADDSONGURL = 'ADDSONGURL';
export { ADDBANNER, ADDPERSONALIZED, ADDPLAYLIST, ADDSONGURL };
