const ADDBANNER = 'ADDBANNER';
const ADDPERSONALIZED = 'ADDPERSONALIZED';
const ADDPLAYLIST = 'ADDPLAYLIST';
const ADDSONGURL = 'ADDSONGURL';
const ADDPLAYNUM = 'ADDPLAYNUM';
export { ADDBANNER, ADDPERSONALIZED, ADDPLAYLIST, ADDSONGURL, ADDPLAYNUM };
