const ADDBANNER = 'ADDBANNER';
const ADDPERSONALIZED = 'ADDPERSONALIZED';
const ADDPLAYLIST = 'ADDPLAYLIST';
const ADDSONGURL = 'ADDSONGURL';
const ADDPLAYNUM = 'ADDPLAYNUM';
const UPDATEAUDIOCONTEXT = 'UPDATEAUDIOCONTEXT';
const ADDMUSICTYPE = 'ADDMUSICTYPE';
export { ADDBANNER, ADDPERSONALIZED, ADDPLAYLIST, ADDSONGURL, ADDPLAYNUM, UPDATEAUDIOCONTEXT, ADDMUSICTYPE };
